### ISSUE TITLE
publication parsing

### ISSUE THREAD

**Issue by faroit** [bmcfee/bmcfee.github.io#3]
Hey Brian,

I am currently in the mood to redo my personal website to include some automated way to render my publications stored in a single central place... which would not be google scholar, as they still don't  offer any API. Also I don't like the way many other academics use jekyll and some hacky bibtex parsers to render their bibliography. 

Now, I saw that you are using a list of custom json for your bibs. I wonder if you have considered either [BibJSON](http://okfnlabs.org/bibjson/) or [CSL-JSON](https://citationstyles.org/) ? Or maybe you know of some open, non-commercial cloud based solution that can host your references and has an API to convert to any format? 

* Here in France, we can use [HAL](https://hal.archives-ouvertes.fr/), which has a nice json API but its only for preprints so it would not serve for older papers
* Semantic-Scholar has an [API](https://api.semanticscholar.org/) but it does not offer bibtex formats
*  ...?

**Comment by bmcfee** [comment]
Nope, hadn't considered that -- didn't even know they existed!  I spent maybe an afternoon poking around the options a few years back when I last redid my site, and hacking my own json format seemed like the path of least resistance.

**Comment by faroit** [comment]
Alrighty. If you are interested, I  can let you know what I chose in the end. Thanks and happy holidays 🎅

**Comment by faroit** [comment]
Btw. I am now using the [zotero api](https://www.zotero.org/support/dev/web_api/v3/start) to host my own publications and request their api to rendering them on [my own site](https://github.com/faroit/website/blob/master/docs/.vuepress/components/publications.vue). Seem to work nicely and leaves all the ugly work at zotero. Also you can nicely edit your citations in their web or desktop UI.

e.g. to get your just your own conference papers:
 
```
https://api.zotero.org/users/6408178/publications/items?format=json&include=data,csljson,bib&style=apa&sort=date&limit=100&itemType=conferencePaper
```

you can include 

*  `data`: zoteros metadata
*  `csljson`: a standardized csl-json
*  `bib`: rendered bib entry in `apa` format

even though `bib` is cool as it returns valid html, its not that practical as you might want to add css classes for authors or title...

**Comment by bmcfee** [comment]
Hah, had forgotten about this thread.  But thanks for the update!
